### ISSUE TITLE
lan口网络非常慢

### ISSUE THREAD

**Issue by tt2024-cmd** [photonicat/rockchip_rk3568_linux_mainline#1]
固件版本：http://dl.photonicat.com/.tmp/rk3568-debian12-with-vm-openwrt.img.gz

烧录固件后，未做任何更改。设备wan口接入路由器，电脑通过网线接入lan口。
电脑IP 为 172.16.0.159
wan（eth0）的ip为 192.168.55.137
lan（eth1）的ip为 172.16.0.1
外网：
上网正常，但是网速非常慢，网速上不去。speedtest.net 测速  速度只有1M。本地网络正常是千M网络，不通过设备测速，可到百M。
内网：
内网2台机器，IP分别为 192.168.55.15 172.16.0.111
在设备上通过curl 下载 172.16.0.111 上的大数据文件，速度正常，可达到70M/S。
在设备上通过curl 下载 192.168.55.15 上的大数据文件，速度异常，不到1M/S。

电脑不通过网线连接设备lan口，通过wifi连接设备，内外网速度相对正常。

设备上openwrt的 /etc/config/network
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP qlen 1000
    link/ether 52:54:00:54:c1:e7 brd ff:ff:ff:ff:ff:ff
    inet 192.168.55.137/24 brd 192.168.55.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fde9:774e:8080:0:5054:ff:fe54:c1e7/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fd2f:29ed:774c:0:5054:ff:fe54:c1e7/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe54:c1e7/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br-lan state UP qlen 1000
    link/ether 52:54:00:2c:86:f2 brd ff:ff:ff:ff:ff:ff
4: eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel state DOWN qlen 1000
    link/ether 52:54:00:2c:18:cc brd ff:ff:ff:ff:ff:ff
7: phy0-ap0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-lan state UP qlen 1000
    link/ether cc:64:1a:71:4b:54 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::ce64:1aff:fe71:4b54/64 scope link 
       valid_lft forever preferred_lft forever
9: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 52:54:00:2c:86:f2 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/24 brd 172.16.0.255 scope global br-lan
       valid_lft forever preferred_lft forever
    inet6 fd92:3578:f4aa::1/60 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fde9:774e:8080:4::1/62 scope global dynamic noprefixroute 
       valid_lft 38629sec preferred_lft 38629sec
    inet6 fe80::5054:ff:fe2c:86f2/64 scope link 
       valid_lft forever preferred_lft forever

设备上debian /etc/network/interfaces
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master br-wan state UP group default qlen 1000
    link/ether a2:49:9f:5a:06:c6 brd ff:ff:ff:ff:ff:ff
    altname end1
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master br-lan state UP group default qlen 1000
    link/ether a2:49:9f:5a:06:c7 brd ff:ff:ff:ff:ff:ff
    altname end0
4: can0: <NOARP,ECHO> mtu 16 qdisc noop state DOWN group default qlen 10
    link/can 
6: br-wan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 2a:41:97:44:32:0f brd ff:ff:ff:ff:ff:ff
    inet6 fde9:774e:8080:0:2841:97ff:fe44:320f/64 scope global dynamic mngtmpaddr 
       valid_lft forever preferred_lft forever
    inet6 fd2f:29ed:774c:0:2841:97ff:fe44:320f/64 scope global dynamic mngtmpaddr 
       valid_lft forever preferred_lft forever
    inet6 fe80::2841:97ff:fe44:320f/64 scope link 
       valid_lft forever preferred_lft forever
7: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether de:ed:fa:09:a9:21 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.2/24 brd 172.16.0.255 scope global br-lan
       valid_lft forever preferred_lft forever
    inet6 fde9:774e:8080:4:dced:faff:fe09:a921/64 scope global dynamic mngtmpaddr 
       valid_lft 38586sec preferred_lft 38586sec
    inet6 fd92:3578:f4aa:0:dced:faff:fe09:a921/64 scope global dynamic mngtmpaddr 
       valid_lft forever preferred_lft forever
    inet6 fe80::dced:faff:fe09:a921/64 scope link 
       valid_lft forever preferred_lft forever
8: virbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:54:00:a5:65:0d brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
9: vnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-wan state UNKNOWN group default qlen 1000
    link/ether fe:54:00:54:c1:e7 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc54:ff:fe54:c1e7/64 scope link 
       valid_lft forever preferred_lft forever
10: vnet1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-lan state UNKNOWN group default qlen 1000
    link/ether fe:54:00:2c:86:f2 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc54:ff:fe2c:86f2/64 scope link 
       valid_lft forever preferred_lft forever
11: vnet2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master virbr0 state UNKNOWN group default qlen 1000
    link/ether fe:54:00:2c:18:cc brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc54:ff:fe2c:18cc/64 scope link 
       valid_lft forever preferred_lft forever

电脑IP
![image](https://github.com/user-attachments/assets/b0ac200f-b7ba-415b-9b94-7cdf1857e184)

期望结果：lan口 内外网 速度正常。

**Comment by supercatexpert** [comment]
将OpenWRT内eth2设置为静态IP(192.168.122.2)，可能是管理口默认的DHCP里面带了网关造成的冲突。
经过测试网速符合预期。

**Comment by tt2024-cmd** [comment]
root@OpenWrt:~# cat /etc/config/network 


config interface 'loopback'
	option device 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'


config globals 'globals'
	option ula_prefix 'fd92:3578:f4aa::/48'


config device
	option name 'br-lan'
	option type 'bridge'
	list ports 'eth1'


config interface 'wan'
	option proto 'dhcp'
	option device 'eth0'


config interface 'wan6'
	option proto 'dhcpv6'
	option metric '2'
	option sourcefilter '0'
	option device 'eth0'


config interface 'lan'
	option device 'br-lan'
	option proto 'static'
	option ipaddr '172.16.0.1'
	option netmask '255.255.255.0'
	option ip6assign '60'
	list dns '114.114.114.114'


config interface 'vnet'
	option proto 'static'
	option device 'eth2'
	option ipaddr '192.168.122.2'
	option netmask '255.255.255.0'

如上面所示：我已经把eth2修改成了静态IP，但是速度还是上不去。

**Comment by supercatexpert** [comment]
能给出你们的网络拓补图么，检查一下是否有环网之类的问题。我们自己测试都是正常的。

**Comment by tt2024-cmd** [comment]
> 能给出你们的网络拓补图么，检查一下是否有环网之类的问题。我们自己测试都是正常的。

网络构建非常简单，光猫->路由器->设备.不会有环网。
你刷完这个固件（http://dl.photonicat.com/.tmp/rk3568-debian12-with-vm-openwrt.img.gz），除了修改eth2为静态IP，还做过其他什么修改吗？
测速的时候，上传几乎为0。wan和lan只要不交互，在各自的网段里速度都是正常。
![image](https://github.com/user-attachments/assets/7ce7f664-9a7e-4649-ae58-08d34a3c9e96)

**Comment by supercatexpert** [comment]
在OpenWRT里面跑一个iperf3服务器，然后LAN口电脑上运行一个iperf3测一下速度看看

**Comment by supercatexpert** [comment]
关闭OpenWRT内网卡的TSO即可: (需要安装ethtool)
ethtool -K eth1 tso off
